In [1]:
#numpy- numeric competition
#pandas - manipulate datasets

In [2]:
#Numpy- to perform mathematical operations faster

In [3]:
#Numpy arrays vs Lists


In [4]:
#Numpy arrays

In [3]:
import numpy as np

In [12]:
np

<module 'numpy' from 'C:\\Users\\khushbu gupta\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\numpy-1.21.2-py3.9-win-amd64.egg\\numpy\\__init__.py'>

In [7]:
lst=[1,2,3]
type(lst)

list

In [17]:
#convert list to a numpy array

#1-D list to numpy array
lst=[1,2,3]
numpy_array=np.array(lst)

In [14]:
numpy_array

array([1, 2, 3])

In [18]:
type(numpy_array)

numpy.ndarray

In [24]:
#multidimensional list to numpy array

lst=[[1,2,3,3],[3,5,7,2],[9,3,44,4.5]]
np_array=np.array(lst)
np_array

array([[ 1. ,  2. ,  3. ,  3. ],
       [ 3. ,  5. ,  7. ,  2. ],
       [ 9. ,  3. , 44. ,  4.5]])

In [25]:
lst

[[1, 2, 3, 3], [3, 5, 7, 2], [9, 3, 44, 4.5]]

In [ ]:
#reshaping the numpy array

In [27]:
np_array.shape

(3, 4)

In [28]:
np_array=np.reshape(np_array,(4,3))

In [29]:
np_array

array([[ 1. ,  2. ,  3. ],
       [ 3. ,  3. ,  5. ],
       [ 7. ,  2. ,  9. ],
       [ 3. , 44. ,  4.5]])

In [30]:
np_array.shape

(4, 3)

In [31]:
#create a numpy array of specific size

In [33]:
np.zeros((4,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [34]:
np.zeros((4,3),dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.ones((4,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [36]:
#random number genertion

In [1]:
num=9

n=input("enter a number")

if num==n:
    print('You win')
else:
    print('you lose')

enter a number2
you lose


In [9]:


rand=np.random.randint(0,9)
rand

1

In [11]:
#shift+tab to know what to write inside brackets
# (2,10,5):5 numbers bw 2 and 10
np.linspace(2,10,5)        

array([ 2.,  4.,  6.,  8., 10.])

In [13]:
#(2,10,7):prints 7 numbers bw 2 and 10

np.linspace(2,10,7)

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [14]:
np.mean(np.linspace(2,10,7))

6.0

In [15]:
np.sqrt(np.linspace(2,10,7))

array([1.41421356, 1.82574186, 2.1602469 , 2.44948974, 2.7080128 ,
       2.94392029, 3.16227766])

In [16]:
array=np.linspace(2,10,7)

In [17]:
array

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [ ]:
#arithematic op on np array

In [18]:
array+2

array([ 4.        ,  5.33333333,  6.66666667,  8.        ,  9.33333333,
       10.66666667, 12.        ])

In [19]:
array*2

array([ 4.        ,  6.66666667,  9.33333333, 12.        , 14.66666667,
       17.33333333, 20.        ])

In [20]:
array/2

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

In [21]:
array-2

array([0.        , 1.33333333, 2.66666667, 4.        , 5.33333333,
       6.66666667, 8.        ])

In [22]:
#same op with list gives error

lst=[1,2,3,4]
lst+2


TypeError: can only concatenate list (not "int") to list

In [30]:
temp_lst=[]
lst=[1,2,3,4]
for i in lst:
    temp=i+2
    print(temp)
    temp_lst.append(temp)
print(temp_lst)

3
4
5
6
[3, 4, 5, 6]


In [31]:
#Pandas
#!pip install pandas-jupyter notebook


In [33]:
import pandas as pd

In [36]:
# df=pd.read_csv("file.csv")

# print(df)                                #prints whole dataset

# print(df.head())                        #prints top 5 rows of dataset

# print(df.head(20))                      #prints top 20 rows of dataset

# print(df['Column_name'])                #prints all the data under column_name column of type-pandas.core.series.Series

# print(df['Column_name'].values)        #returnd data of type numpy array            

In [37]:
#returns data in numpy array format

# country=df['Country'].values
# age=df['Age'].values
# salary=df['Salary'].values


# len(country)
# len(age)
# len(salary)

In [51]:
# data=df.values
# data         #returns a 2-D array/List format of dataframe 
# data[:,:]

In [44]:
lst=[1,2,3,4,5]
lst[2:4]

[3, 4]

In [47]:
lst=[[1,2,3],
     [2,5,6],
     [5,6,7,8]]
lst[:]

[[1, 2, 3], [2, 5, 6], [5, 6, 7, 8]]

In [50]:
#in multidimensional lists
lst[:,:]          #lst[deals with rows ,deals with columns]

[[1, 2, 3], [2, 5, 6], [5, 6, 7, 8]]

In [53]:
#in range 1 to 99
rand=np.random.randint(1,100)
rand

0

In [54]:
lst=[1,2,3]
lst+=7

TypeError: 'int' object is not iterable

In [58]:
lst=[[1,2,3,3],[1,2,3,5,]]
np_array=np.array(lst)
np_array.shape

(2, 4)

In [62]:
np_array.reshape((2,2),order='C')

ValueError: cannot reshape array of size 8 into shape (2,2)